---
- name: Durée de fonctionnement
  #hosts: "{{ machine }}"
  #test
  hosts: all
  tasks:
  - name: Obtenir la durée
    shell: uptime | awk '{print $1}'
    when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
    register: resultat

  - debug:
      msg: La durée est de {{resultat.stdout}}
