- include_vars: "../vars/main.yml"

- name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
  copy:
    content: hello worldn
    dest: /tmp/testfile.txt

- name: Gather facts on listening ports
  listen_ports_facts:

- name: List TCP ports
  ansible.builtin.debug:
    msg: "{{ ansible_facts.tcp_listen  | map(attribute='port') | sort | list }}"


- name: Move openv to openv.old
  command: 
    cmd: mv {{ install_dir }} {{ install_dir.save }} 
    creates: "{{ install_dir.save }}" 
    removes: "{{ install_dir }}"
      
- name: Crée un rep d'installation s'il n'existe pas
  file: 
    path: "{{ install_dir }}"
    state: directory 
    owner: root
    group: root
    mode: '0755'

